Homeworks
guillotine666/frontend pull request #23
Opened 2021-05-08 18:26 UTC by guillotine666

Add solutions and tests for all homeworks.

2021-05-09 12:34 UTC, vvscode commented on .github/workflows/sanity-check.yml
> +      - "master"
это еще почему?

2021-05-09 12:34 UTC, vvscode commented on .github/workflows/sanity-check.yml
> +      - "*"
а это просто лишнее - ты ничего нового к `pull_request` не добавил

2021-05-09 12:35 UTC, vvscode commented on package.json
> +    "*.js": "npm run lint:fix",
нет, и я на занятии объяснял почему так не правильно

повторю - в проекте 1000 файлов, ты поменял 100 и хочешь закоммитить 10 - сколько файлов будет обработано?

2021-05-09 12:36 UTC, vvscode commented on src/hemoWerk10/index.test.js
> +  });
https://jestjs.io/ru/docs/api#testeachtablename-fn-timeout

2021-05-09 12:37 UTC, vvscode commented on src/homeWork1/index.test.js
> +  beforeAll(() => {
лучше это делать в beforeEach

2021-05-09 12:38 UTC, vvscode commented on src/homeWork1/index.test.js
> +      expect(console.log).toHaveBeenCalledWith(-2, -0);
а лучше - потому что jest.fn накапливает историю вызовов

2021-05-09 12:38 UTC, vvscode commented on src/homeWork2/index.js
> +    case 1:
а можешь придумать, как сделать это проще?

2021-05-10 10:27 UTC, guillotine666 commented on .github/workflows/sanity-check.yml
> +      - "master"
Если у нас настроены проверки PR, то в мастер гарантированно полетит код, только прошедший проверки. Поэтому решил, что мастер можно не проверять

2021-05-10 10:28 UTC, malkops commented on .github/workflows/sanity-check.yml
> +      - "*"
Понял почему, уберу

2021-05-10 10:33 UTC, guillotine666 commented on src/homeWork2/index.js
> +    case 1:
Значения можно хранить названия месяцев в массиве и брать их по индексу. Либо создавать объект с введенным месяцем и брать название из объекта. Первый вариант выглядит самым простым

2021-05-10 10:35 UTC, malkops commented on package.json
> +    "*.js": "npm run lint:fix",
Будут обработаны все 1000 файлов, вспомнил что об этом ты говорил, но не отразил, когда настройку делал. Исправлю

2021-05-10 10:37 UTC, malkops commented on src/hemoWerk10/index.test.js
> +  });
Исправлю, с each выглядит элегантнее, спасибо за наводку

2021-05-10 10:39 UTC, guillotine666 commented on src/homeWork1/index.test.js
> +  beforeAll(() => {
Понятно почему, исправлю

2021-05-10 17:56 UTC, guillotine666 commented on .github/workflows/sanity-check.yml
> +      - "master"
Здесь понял почему плохо - вдруг кто-то решит напрямую в мастер запушить (что ужасно, но не исключено)

2021-05-18 07:58 UTC, vvscode commented on src/hemoWerk10/index.test.js
> +});
как название теста соотносится с тем, что внутри теста?

2021-05-18 07:59 UTC, vvscode commented on src/homeWork1/index.test.js
> +  describe("first task (console.log sum and multiply)", () => {
https://dev.to/bgord/simplify-repetitive-jest-test-cases-with-test-each-310m

2021-05-18 21:37 UTC, AntiHero requested changes

2021-05-18 21:37 UTC, AntiHero commented on package.json
>      "babel-jest": "^26.6.3"
а это почему не перенёс?

2021-05-18 21:37 UTC, AntiHero commented on src/homeWork2/index.test.js
> +    beforeEach(() => {
это можно было наверх всё вынести, чтобы не писать в каждом describe beforeEach, afterEach

2021-05-18 21:37 UTC, AntiHero commented on src/homeWork7/index.test.js
> +    input.value = "first";
можно в цикл вынести повторяющийся код, ведь текст по сути не важен, который ты вводишь, важно, что количество параграфов увеличиваются максимум до пяти

2021-05-18 21:37 UTC, AntiHero commented on src/homeWork8/index.js
> +    (d.getHours() * 3600 + d.getMinutes() * 60 + d.getSeconds()) / 60
тебе надо было минуты посчитать вроде как по заданию, т.е. ты вначале переводишь всё в секунды, а потом делишь на 60? не проще сложить часы умножные на часы и кол-во минут?

2021-05-19 05:04 UTC, merged